name: production-workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: master

      # Setup node
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Get cache directory
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

        # Cache yarn
      - name: Cache yarn
        id: cache-yarn
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: Install Dependencies
        # if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # Build static
      - name: Build static
        run: yarn run build --mode production
        env:
          NODE_ENV: production
          BACK_URI: ${{ secrets.PROD_BACK_URI }}

      # Copy project
      - name: Copy project
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key : ${{ secrets.SERVER_KEY }}
          source: "./, !./node_modules"
          target: ./${{ github.event.repository.name }}_prod
          rm: true

      # Deploy project
      
      - name: Deploy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          # -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
          script: |
            cd /home/reg/${{ github.event.repository.name }}_prod/nginx/front-prod
            docker-compose up -d -V --no-deps
            cd /home/reg/${{ github.event.repository.name }}_prod/nginx/reverse-proxy
            docker-compose up -d --build

  release:
    needs: deploy
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DIST_TAR_PATH: dist/dist.tar.gz
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
            @semantic-release/npm