version: '3'
services:
  front-prod:
    container_name: front-prod
    image: nginx:1.12
    networks:
     - application_prod_network
    volumes:
      - ./dist:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"

networks:
  application_prod_network:
    driver: bridge
    name: application_prod_network